#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --top-module top -I./include ./Mux/*.sv ./Pipelining/*.sv ./HazardControl/*.sv ./Control/*.sv  ./Memory/*.sv  ./PC/*.sv ./Alu/*.sv top.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation file
obj_dir/Vtop
