#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f oldDataMem.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --top-module oldDataMem -I./include oldDataMem.sv --exe oldDataMem_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VoldDataMem.mk VoldDataMem

#run executable simulation file
obj_dir/VoldDataMem
